apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: message-dev-tls-secret
  namespace: message-dev
spec:
  secretName: message-dev-tls-secret
  dnsNames:
  - message-dev.gccollab.ca
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - message-dev.gccollab.ca
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer