apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: message-ingress
  namespace: message-dev
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  tls:
  - hosts:
    - message-dev.gccollab.ca
    secretName: message-secret
  rules:
  - host: message-dev.gccollab.ca
    http:
      paths:
      - path: /
        backend:
          serviceName: message
          servicePort: 8005
