apiVersion: v1
kind: Service
metadata:
  name: message
  namespace: dev
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 8005
  selector: 
    app: message
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: message-deployment
  namespace: dev
spec:
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: message
    spec:
      containers:
      - name: message
        image: rocketchat/rocket.chat:latest
        ports:
        - containerPort: 8005
        env:
        - name: "PORT"
          value: 8005
        - name: "ROOT_URL"
          value: "https://message.gccollab.ca"
        - name: "MONGO_URL"
          value: "mongodb://mongo:27017/rocketchat"
        - name: "MONGO_OPLOG_URL"
          value: "mongodb://mongo:27017/local"
        livenessProbe:
          httpGet:
            path: /home
            port: 8005
          initialDelaySeconds: 30
          periodSeconds: 3
          timeoutSeconds: 1
          failureThreshold: 3
        volumeMounts:
        - mountPath: /app/uploads
          name: message-data-volume
      volumes:
      - name: message-data-volume
        persistentVolumeClaim:
          claimName: dev-message-data-volume-claim
