apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: collab-dev-tls-secret
  namespace: dev
spec:
  secretName: collab-dev-tls-secret
  dnsNames:
  - dev.gccollab.ca
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - dev.gccollab.ca
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer