kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: managed-premium-xfs
provisioner: kubernetes.io/azure-disk
parameters: 
  kind: Managed
  storageaccounttype: Premium_LRS
  fsType: xfs
