apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-data-volume-claim
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 5Gi
