kind: PersistentVolume
apiVersion: v1
metadata:
  name: collab-chat-volume
  namespace: prod
spec:
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: "Retain"
  storageClassName: collab-chat
  accessModes:
    - ReadWriteMany
  azureFile:
    secretName: azure-secret
    # a file share with this name needs to be created manually
    shareName: collab-chat
    readOnly: false
  mountOptions:
    - dir_mode=0777
    - file_mode=0666
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collab-chat-volume-claim
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: collab-chat
  resources:
    requests:
      storage: 10Gi
