apiVersion: v1
kind: Service
metadata:
  name: collab
  namespace: prod
  labels:
    app: collab
spec:
  ports:
    - protocol: TCP
      port: 80
  selector: 
    app: collab
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: collab-deployment
  namespace: prod
spec:
  #replicas: 1    # let the autoscaler handle this
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: collab
    spec:
      containers:
      - name: collab
        image: phanoix/gcconnex:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /splash/
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /splash/
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 60
          timeoutSeconds: 15
          failureThreshold: 3
        resources:
          requests:
            memory: "1024Mi"
            cpu: "0.5"
          limits:
            memory: "2048Mi"
            cpu: "0.75"
        env:
        - name: "DOCKER"
          value: ""
        - name: "HOME"
          value: "/var/www/html"
        - name: "DBHOST"
          value: "collab-db"
        - name: "WWWROOT"
          value: "http://gccollab.ca/"
        volumeMounts:
        - mountPath: /sites/gccollab_data
          name: collab-data-volume
        - mountPath: /var/www/html/engine/settings.php
          subPath: settings.php
          name: collab-settings
        - mountPath: /var/www/html/.htaccess
          subPath: htaccess
          name: collab-settings
      - name: collab-memcached
        image: memcached:alpine
        ports:
        - containerPort: 11211
        resources:
          requests:
            memory: "64Mi"
            cpu: "0.05"
          limits:
            memory: "96Mi"
            cpu: "0.2"
      volumes:
      - name: collab-data-volume
        persistentVolumeClaim:
          claimName: collab-data-volume-claim
      - name: collab-settings
        configMap:
          name: collab-config
