apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-data-volume-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kubevolumesstore
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiki-db-volume-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kubevolumesstore
  resources:
    requests:
      storage: 2Gi