apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-backup-script
  namespace: prod
  labels:
    app: mongo-backup
data:
  script.sh: |
    echo "Started backing up database"
    DATE=$(date +%Y%m%d%H%M%S)
    mongo ///// find secondary instance
    echo "Pause secondary"
    mongo db.fsyncLock()
    echo "Create snapshot"
    curl -X PUT -T /${DATE}.sql.gz -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "${BLOB_URL}"
    echo "Resume secondary"
    db.fsyncLock()
    echo "Finished database backup"
