apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-backup-script
  namespace: prod
  labels:
    app: mongo-backup
data:
  script.sh: |
    echo "Started backing up database"
    DATE=$(date +%Y%m%d%H%M%S)
    mongo ///// find secondary instance
    echo "Pause secondary"
    mongo db.fsyncLock()
    echo "Create snapshot"
    curl -X PUT -T '{ "properties": { "creationData": { "createOption": "Copy", "sourceUri": "/subscriptions/{subscriptionId}/resourceGroups/{YourResourceGroup}/providers/Microsoft.Compute/disks/{YourManagedDiskName}" } }, "location": "canadaeast" }' \
 -H "x-ms-date: $(date -u)"  "https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Compute/snapshots/{snapshotName}?api-version={api-version}"
    echo "Resume secondary"
    db.fsyncLock()
    echo "Finished database backup"
