apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-backup-script
  namespace: prod
  labels:
    app: mongo-backup
data:
  script.sh: |
    function jsonValue() {
      KEY=$1
      num=$2
      awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'$KEY'\042/){print $(i+1)}}}' | tr -d '"' | sed -n ${num}p
    }
    echo "Started backing up database"
    DATE=$(date +%Y%m%d%H%M%S)
    for ((i = 0; i < 2; ++i)); 
    do 
      if [mongo --host=message-db-mongodb-replicaset-$i.message-db-mongodb-replicaset --eval="printjson(rs.isMaster())" | grep '"secondary" : true']
        then
          N=$i
      fi
    done
    echo "Pause secondary"
    mongo --host=message-db-mongodb-replicaset-$N.message-db-mongodb-replicaset --eval="db.fsyncLock()"
    echo "Create snapshot"
    TOKEN=`curl -X POST -d "grant_type=client_credentials&client_id=${APP_ID}&client_secret=${PASSWORD}&resource=https%3A%2F%2Fmanagement.azure.com%2F" https://login.microsoftonline.com/${TENANT_ID}/oauth2/token` | jsonValue access_token 1
    curl -X PUT -T '{ "properties": { "creationData": { "createOption": "Copy", "sourceUri": "/subscriptions/{SUBSCRIPTION_ID}/resourceGroups/{RESOURCE_GROUP}/providers/Microsoft.Compute/disks/{DISK_NAME}" } }, "location": "canadaeast" }' \
 -H "x-ms-date: $(date -u)" -H "Content-type: application/json" -H "Authorization: ${TOKEN}" "https://management.azure.com/subscriptions/{SUBSCRIPTION_ID}/resourceGroups/{RESOURCE_GROUP}/providers/Microsoft.Compute/snapshots/${DATE}?api-version=2018-06-01"
    echo "Resume secondary"
    mongo --host=message-db-mongodb-replicaset-$N.message-db-mongodb-replicaset --eval="db.fsyncLock()"
    echo "Finished database backup"
