apiVersion: v1
kind: Service
metadata:
  name: message
  namespace: prod
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 8005
  selector: 
    app: message
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: message-deployment
  namespace: prod
spec:
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: message
    spec:
      containers:
      - name: message
        image: rocketchat/rocket.chat:0.64.1
        ports:
        - containerPort: 8005
        env:
        - name: "PORT"
          value: "8005"
        - name: "ROOT_URL"
          value: "https://message.gccollab.ca/"
        - name: "MONGO_URL"
          value: "mongodb://message-db-mongodb-replicaset:27017/rocketchat?replicaSet=rs0"
        - name: "MONGO_OPLOG_URL"
          value: "mongodb://message-db-mongodb-replicaset:27017/local?replicaSet=rs0"
        readinessProbe:
          httpGet:
            path: /
            port: 8005
          initialDelaySeconds: 10
          periodSeconds: 6
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8005
          initialDelaySeconds: 60
          periodSeconds: 7
          timeoutSeconds: 10
          failureThreshold: 5
        resources:
          requests:
            memory: "400Mi"
            cpu: "0.25"
          limits:
            memory: "800Mi"
            cpu: "1"
        volumeMounts:
        - mountPath: /app/uploads
          name: message-data-volume
      volumes:
      - name: message-data-volume
        persistentVolumeClaim:
          claimName: message-data-volume-claim
