apiVersion: v1
kind: Service
metadata:
  name: message
  namespace: prod
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 8005
  selector: 
    app: message
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: message-deployment
  namespace: prod
spec:
  replicas: 3
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: message
    spec:
      containers:
      - name: message
        image: rocketchat/rocket.chat:0.71.0
        ports:
        - containerPort: 8005
        env:
        - name: "INSTANCE_IP"
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: "PORT"
          value: "8005"
        - name: "ROOT_URL"
          value: "https://message.gccollab.ca/"
        - name: "DISABLE_PRESENCE_MONITOR"
          value: "true"
        - name: "MONGO_URL"
          value: "mongodb://message-db-mongodb-replicaset-0.message-db-mongodb-replicaset:27017,message-db-mongodb-replicaset-1.message-db-mongodb-replicaset:27017/rocketchat?replicaSet=rs0&readPreference=nearest"
        - name: "MONGO_OPLOG_URL"
          value: "mongodb://message-db-mongodb-replicaset-0.message-db-mongodb-replicaset:27017,message-db-mongodb-replicaset-1.message-db-mongodb-replicaset:27017/local?replicaSet=rs0"
        readinessProbe:
          httpGet:
            path: /api/v1/info
            port: 8005
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 4
          failureThreshold: 3
        # due to sticky sessions this has to be very generous, a restart in one pod that's just slow can cause more problems than it solves
        livenessProbe:  
          httpGet:
            path: /api/v1/info
            port: 8005
          initialDelaySeconds: 360
          periodSeconds: 12
          timeoutSeconds: 12
          failureThreshold: 12
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1.3"
          limits:
            memory: "2048Mi"
            cpu: "1.4"
        volumeMounts:
        - mountPath: /app/uploads
          name: message-data-volume
      volumes:
      - name: message-data-volume
        persistentVolumeClaim:
          claimName: message-data-volume-claim
