apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: account-dev-tls-secret
  namespace: dev
spec:
  secretName: account-dev-tls-secret
  dnsNames:
  - account-dev.gccollab.ca
  acme:
    config:
    - http01:
        ingressClass: istio
      domains:
      - account-dev.gccollab.ca
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
