kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: matomo-disk
  namespace: analytics
  labels:
    name: matomodb
    app: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi