apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: account-tls-secret
spec:
  secretName: account-tls-secret
  dnsNames:
  - account.gccollab.ca
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - account.gccollab.ca
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer