apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: account-db-backup
  namespace: prod
spec:
  schedule: 0 3 * * *
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  suspend: false
  jobTemplate:
    metadata:
      labels:
        app: account-db-backup
        cronjob-name:  account-pgdump
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: pgdump
            image: postgres:10
            command: ["/bin/bash", "/scripts/backup.sh"]
            envFrom
            - secretRef:
                name: account-pgdump-env
            volumeMounts:
            - name: pgdump-script
              mountPath: /scripts
          volumes:
          - name: pgdump-script
            configMap:
              name: pgdump-script
