apiVersion: v1
kind: ConfigMap
metadata:
  name: account-pgdump-script
  namespace: prod
  labels:
    app: account-pgdump-script
data:
  script.sh: |
    echo "Started backing up database"
    DATE=$(date +%Y%m%d%H%M%S)
    pg_dump -h "$HOSTNAME" -U "$USERNAME" postgres > /${DATE}.sql
    curl curl -X PUT -T /${DATE}.sql -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "${BLOB_URL}"
    echo "Finished database backup"
