apiVersion: v1
kind: Secret
metadata:
  name: account-env
  labels:
    app: account
type: Opaque
data:
  secret-key: supersecret
  db-password: postgres
  email-user: emailuser
  email-password: emailpass
  freshdesk-secret-key: supersecret!