apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wiki-tls-secret
spec:
  secretName: wiki-tls-secret
  dnsNames:
  - wiki.gccollab.ca
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - wiki.gccollab.ca
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer