apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: message-tls-secret
spec:
  secretName: message-tls-secret
  dnsNames:
  - message.gccollab.ca
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - message.gccollab.ca
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer